version: 2

updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: weekly
    assignees:
      - PHLAK

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    assignees:
      - PHLAK

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    assignees:
      - PHLAK
